// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATzOY44S-OyK1tCR-ugGj9hUua-DUMbPY',
    appId: '1:771744917375:web:bb434e0f9a24ddbb7f9c4a',
    messagingSenderId: '771744917375',
    projectId: 'mubashar-task',
    authDomain: 'mubashar-task.firebaseapp.com',
    storageBucket: 'mubashar-task.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmycqrtOoDA_ieHW-_NCUqIdg9J315PFk',
    appId: '1:771744917375:android:35aaedff6d7c52947f9c4a',
    messagingSenderId: '771744917375',
    projectId: 'mubashar-task',
    storageBucket: 'mubashar-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCykik__4134liYuyPI6jUUSkSFlmEjiSo',
    appId: '1:771744917375:ios:92240bba13f5272b7f9c4a',
    messagingSenderId: '771744917375',
    projectId: 'mubashar-task',
    storageBucket: 'mubashar-task.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCykik__4134liYuyPI6jUUSkSFlmEjiSo',
    appId: '1:771744917375:ios:92240bba13f5272b7f9c4a',
    messagingSenderId: '771744917375',
    projectId: 'mubashar-task',
    storageBucket: 'mubashar-task.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATzOY44S-OyK1tCR-ugGj9hUua-DUMbPY',
    appId: '1:771744917375:web:02ae2374a1235abc7f9c4a',
    messagingSenderId: '771744917375',
    projectId: 'mubashar-task',
    authDomain: 'mubashar-task.firebaseapp.com',
    storageBucket: 'mubashar-task.appspot.com',
  );
}
